# Generated by Django 4.2.2 on 2023-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverID', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('carID', models.CharField(max_length=200)),
            ],
        ),
    ]
