# Generated by Django 4.2.2 on 2023-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_carid_driver_vehicleid_alter_driver_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='maritalStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Seperated', 'Seperated')], default='Single', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phoneNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
