# Generated by Django 4.2.2 on 2023-06-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_driver_maritalstatus_alter_driver_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='homeAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='maritalStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Seperated', 'Seperated'), ('Divorced', 'Divorced')], default='Single', max_length=100),
        ),
    ]
